// English / Bengali / Hindi -- most staff read Bengali or Hindi, not English.
export const L = {
  staffApp: "Staff App / স্টাফ অ্যাপ / स्टाफ ऐप",
  username: "Username / ইউজারনেম / यूज़रनेम",
  pin: "PIN / পিন / पिन",
  login: "Login / লগইন / लॉगिन",
  logout: "Logout",
  owner: "Owner / মালিক / मालिक",
  staff: "Staff / স্টাফ / स्टाफ",
  requestsTab: "Requests / অনুরোধ / अनुरोध",
  stockTab: "Stock / স্টক / स्टॉक",
  newRequest: "New Request / নতুন অনুরোধ / नया अनुरोध",
  item: "Item / জিনিস / सामान",
  quantityOptional: "Quantity / পরিমাণ (optional) / मात्रा (optional)",
  urgent: "Urgent / জরুরি / ज़रूरी",
  noteOptional: "Note / নোট (optional) / नोट (optional)",
  cancel: "Cancel / বাতিল / रद्द करें",
  send: "Send / পাঠান / भेजें",
  pickOrType: "Pick or type an item / জিনিস বাছুন বা লিখুন / सामान चुनें",
  noRequestsYet: "No requests yet / এখনো কোনো অনুরোধ নেই / अभी कोई अनुरोध नहीं",
  pending: "Pending / মুলতুবি / लंबित",
  approved: "Approved / অনুমোদিত / स्वीकृत",
  rejected: "Rejected / প্রত্যাখ্যাত / अस्वीकृत",
  fulfilled: "Purchased / কেনা হয়েছে / खरीदा गया",
  ownerNote: "Owner note / মালিকের নোট / मालिक का नोट",
  waitingPurchase: "Waiting to be purchased / কেনার অপেক্ষায় / खरीद का इंतज़ार",
  notePlaceholder: "Note (optional) / নোট / नोट",
  reject: "Reject / প্রত্যাখ্যান / अस्वीकार",
  approve: "Approve / অনুমোদন করুন / स्वीकृत करें",
  loading: "Loading...",
  under3Days: "Under 3 days cover / ৩ দিনের কম মজুত / 3 दिन से कम स्टॉक",
  daysLeft: "days left / দিন বাকি / दिन बचे",
  overdue: "Overdue / মেয়াদ পেরিয়েছে / समय निकल गया",
  noCountYet: "No stock count yet / এখনো গণনা হয়নি / अभी तक गिनती नहीं",
  updateCount: "Update count / মজুত হালনাগাদ করুন / मात्रा दर्ज करें",
  requestBtn: "Request / অনুরোধ পাঠান / अनुरोध भेजें",
  save: "Save / সংরক্ষণ করুন / सेव करें",
  nothingLow: "Nothing running low / কিছুই কম নেই / कुछ भी कम नहीं",
  savedToast: "Stock updated / স্টক আপডেট হয়েছে / स्टॉक अपडेट हो गया",
  by: "By",
  gasTab: "Gas / গ্যাস / गैस",
  gasTitle: "Gas cylinders / গ্যাস সিলিন্ডার / गैस सिलेंडर",
  tandoor: "Tandoor / তন্দুর / तंदूर",
  kitchen: "Kitchen / রান্নাঘর / रसोई",
  lastNight: "Last night",
  lastReading: "Last reading",
  onTheScale: "on the scale",
  newCylinder: "New cylinder fitted today / নতুন সিলিন্ডার / नया सिलेंडर",
  saveBoth: "Save both / সংরক্ষণ / सेव करें",
  saveGas: "Save / সংরক্ষণ / सेव करें",
  weighHint: "Weigh the whole cylinder on the scale. The empty cylinder (20 kg) is subtracted for you.",
  weighBoth: "Weigh both cylinders first. / দুটো সিলিন্ডারই ওজন করুন / दोनों सिलेंडर तौलें",
  heavier: "kg heavier than last time. Was a new cylinder fitted? Tick the box. / নতুন সিলিন্ডার? / नया सिलेंडर?",
  lighterThanEmpty: "Less than an empty cylinder (20 kg). Check the scale. / ওজন আবার দেখুন / वज़न फिर देखें",
  usedSince: "Used",
  gasLeft: "gas left",
  newHas: "New cylinder ·",
  gasDone: "Both cylinders logged / দুটোই লেখা হয়েছে / दोनों दर्ज हो गए",
  almostEmpty: "is almost empty. Keep a full one ready. The owner has been told. / প্রায় শেষ / लगभग खत्म",
  edit: "Change / বদলান / बदलें",
  gasReminderTitle: "Weigh both gas cylinders / দুটো গ্যাস সিলিন্ডার ওজন করুন / दोनों गैस सिलेंडर तौलें",
  gasReminderBody: "Tandoor + Kitchen. Put each on the scale and type the weight. 1 minute.",
  requestItem: "Request an item / জিনিস চাই / सामान मँगाएँ",
  typeItemName: "Type the item name / জিনিসের নাম লিখুন / सामान का नाम लिखें",
  nameOnlyHint: "Just the name. The owner decides how much to buy. / শুধু নাম লিখুন / सिर्फ़ नाम लिखें",
  runningOutTap: "Running out · tap to send / শেষ হয়ে আসছে / खत्म होने वाला",
  allItems: "All items / সব জিনিস / सभी सामान",
  matches: "Matches / মিল / मिलान",
  sendAsTyped: "Not in the list · send as typed / তালিকায় নেই / सूची में नहीं",
  alreadyRequested: "Already requested / আগেই চাওয়া হয়েছে / पहले ही माँगा गया",
  sentToOwner: "sent to the owner / মালিককে পাঠানো হয়েছে / मालिक को भेजा गया",
  undo: "Undo / ফেরান / वापस लें",
  myRequests: "My requests / আমার অনুরোধ / मेरे अनुरोध",
  statusSent: "Sent / পাঠানো হয়েছে / भेजा गया",
  statusNotNeeded: "Not needed / দরকার নেই / ज़रूरत नहीं",
  ownerDeciding: "owner deciding / মালিক দেখছেন / मालिक तय कर रहे हैं",
  out: "out / শেষ / खत्म",
  // Nightly stock count
  countTab: "Count / গণনা / गिनती",
  lowTab: "Low stock / কম স্টক / कम स्टॉक",
  tonightTitle: "Tonight's stock count / আজকের স্টক গণনা / आज की स्टॉक गिनती",
  fullCountTitle: "Monday full count / সোমবার সম্পূর্ণ গণনা / सोमवार पूरी गिनती",
  dailySub: "vegetables, dairy, frozen + anything running low",
  fullCountSub: "every item, once a week",
  items: "items / জিনিস / सामान",
  doneWord: "done / শেষ / पूरा",
  savedWord: "saved / সংরক্ষিত / सेव",
  takesAbout: "about 10 minutes",
  startCount: "Start count / শুরু করুন / शुरू करें",
  continueCount: "Continue / চালিয়ে যান / जारी रखें",
  lastCountLabel: "Last count",
  reminderLabel: "Reminder",
  every10pm: "Every day 10:00 PM",
  expected: "Expected about / আনুমানিক / लगभग",
  lastCount: "last count",
  neverCounted: "Never counted / কখনো গণনা হয়নি / कभी नहीं गिना",
  same: "Same / একই / वही",
  badNumber: "Enter a number / সংখ্যা লিখুন / संख्या लिखें",
  autoSaveHint: "Each number saves by itself / প্রতিটি সংখ্যা নিজেই সংরক্ষিত হয় / हर संख्या अपने आप सेव होती है",
  doneTonight: "Done for today / আজকের কাজ শেষ / आज का काम पूरा",
  itemsCounted: "items counted",
  noReminderUntil: "No reminder until tomorrow 10 PM.",
  runningOut: "Running out / ফুরিয়ে যাচ্ছে / खत्म हो रहा है",
  reviewCounts: "Review counts / গণনা দেখুন / गिनती देखें",
  ownerOnly: "Owner options · staff don't see these",
  correctQty: "Correct the quantity",
  disableItem: "Disable item (no longer used)",
  disableConfirm: "Disable",
  disableReasonPrompt: "It disappears from counts, forecast and requests. Reason:",
  noLongerUsed: "No longer used",
  disabled: "disabled",
  reminderTitle: "Time for tonight's stock count / রাতের স্টক গণনার সময় / रात की स्टॉक गिनती का समय",
  reminderBody: "items · about 10 minutes. Tap to start.",
  reminderBodyFull: "Monday full count: every item. Tap to start.",
};
