// English / Bengali / Hindi -- most staff read Bengali or Hindi, not English.
export const L = {
  staffApp: "Staff App / স্টাফ অ্যাপ / स्टाफ ऐप",
  username: "Username / ইউজারনেম / यूज़रनेम",
  pin: "PIN / পিন / पिन",
  login: "Login / লগইন / लॉगिन",
  logout: "Logout",
  owner: "Owner / মালিক / मालिक",
  staff: "Staff / স্টাফ / स्टाफ",
  requestsTab: "Requests / অনুরোধ / अनुरोध",
  stockTab: "Stock / স্টক / स्टॉक",
  newRequest: "New Request / নতুন অনুরোধ / नया अनुरोध",
  item: "Item / জিনিস / सामान",
  quantityOptional: "Quantity / পরিমাণ (optional) / मात्रा (optional)",
  urgent: "Urgent / জরুরি / ज़रूरी",
  noteOptional: "Note / নোট (optional) / नोट (optional)",
  cancel: "Cancel / বাতিল / रद्द करें",
  send: "Send / পাঠান / भेजें",
  pickOrType: "Pick or type an item / জিনিস বাছুন বা লিখুন / सामान चुनें",
  noRequestsYet: "No requests yet / এখনো কোনো অনুরোধ নেই / अभी कोई अनुरोध नहीं",
  pending: "Pending / মুলতুবি / लंबित",
  approved: "Approved / অনুমোদিত / स्वीकृत",
  rejected: "Rejected / প্রত্যাখ্যাত / अस्वीकृत",
  fulfilled: "Purchased / কেনা হয়েছে / खरीदा गया",
  ownerNote: "Owner note / মালিকের নোট / मालिक का नोट",
  waitingPurchase: "Waiting to be purchased / কেনার অপেক্ষায় / खरीद का इंतज़ार",
  notePlaceholder: "Note (optional) / নোট / नोट",
  reject: "Reject / প্রত্যাখ্যান / अस्वीकार",
  approve: "Approve / অনুমোদন করুন / स्वीकृत करें",
  loading: "Loading...",
  under3Days: "Under 3 days cover / ৩ দিনের কম মজুত / 3 दिन से कम स्टॉक",
  daysLeft: "days left / দিন বাকি / दिन बचे",
  noCountYet: "No stock count yet / এখনো গণনা হয়নি / अभी तक गिनती नहीं",
  updateCount: "Update count / মজুত হালনাগাদ করুন / मात्रा दर्ज करें",
  requestBtn: "Request / অনুরোধ পাঠান / अनुरोध भेजें",
  save: "Save / সংরক্ষণ করুন / सेव करें",
  nothingLow: "Nothing running low / কিছুই কম নেই / कुछ भी कम नहीं",
  by: "By",
};
